//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_UNDERGRAD_PROGRAM
    {
        public MD_UNDERGRAD_PROGRAM()
        {
            this.APPOINTMENT_ROLE = new HashSet<APPOINTMENT_ROLE>();
        }
    
        public int MD_UNDERGRAD_PROGRAM_ID { get; set; }
        public string MD_UNDERGRAD_PROGRAM_DESC { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_TS { get; set; }
        public string LAST_UPDT_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TS { get; set; }
        public string CREATED_USER { get; set; }
    
        public virtual ICollection<APPOINTMENT_ROLE> APPOINTMENT_ROLE { get; set; }
    }
}
