//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYEE
    {
        public PAYEE()
        {
            this.PAYMENT_INFO = new HashSet<PAYMENT_INFO>();
        }
    
        public int PAYEE_ID { get; set; }
        public int PERSON_ID { get; set; }
        public int PAYEE_TYPE_ID { get; set; }
        public Nullable<bool> ADDRESS_IS_MAILING_IND { get; set; }
        public int PAYEE_ORGANIZATION_ID { get; set; }
        public string DELIMITER_CHARACTER { get; set; }
        public Nullable<int> GST_STATUS_ID { get; set; }
        public string BUSINESS_NUMB { get; set; }
        public string SMALL_SUPPLIER_STATUS { get; set; }
        public string GST_NUMB { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_TS { get; set; }
        public string LAST_UPDT_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TS { get; set; }
        public string CREATED_USER { get; set; }
    
        public virtual PAYEE_TYPE PAYEE_TYPE { get; set; }
        public virtual ICollection<PAYMENT_INFO> PAYMENT_INFO { get; set; }
    }
}
