//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYEE_TYPE
    {
        public PAYEE_TYPE()
        {
            this.PAYEEs = new HashSet<PAYEE>();
        }
    
        public int PAYEE_TYPE_ID { get; set; }
        public string PAYEE_TYPE_DESC { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_TS { get; set; }
        public string LAST_UPDT_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TS { get; set; }
        public string CREATED_USER { get; set; }
    
        public virtual ICollection<PAYEE> PAYEEs { get; set; }
    }
}
