//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.TTPS_CONTACT_INFO = new HashSet<TTPS_CONTACT_INFO>();
        }
    
        public int PERSON_ID { get; set; }
        public string UBC_ID { get; set; }
        public Nullable<bool> IS_ACTIVE_PROFILE { get; set; }
        public Nullable<bool> IS_RETIRED { get; set; }
        public Nullable<bool> HAS_ALTERNATE_NAME { get; set; }
        public string PREFERRED_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NAME_SUFFIX { get; set; }
        public Nullable<bool> SALUTATION_ID { get; set; }
        public string ALTERNATE_FIRST_NAME { get; set; }
        public string ALTERNATE_MIDDLE_NAME { get; set; }
        public string ALTERNATE_LAST_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public int GENDER_ID { get; set; }
        public Nullable<int> OCCUPATION_ID { get; set; }
        public int PAYMENT_ARRANGMENT_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_TS { get; set; }
        public string LAST_UPDT_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TS { get; set; }
        public string CREATED_USER { get; set; }
    
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual OCCUPATION OCCUPATION { get; set; }
        public virtual PAYMENT_ARRANGEMENT PAYMENT_ARRANGEMENT { get; set; }
        public virtual ICollection<TTPS_CONTACT_INFO> TTPS_CONTACT_INFO { get; set; }
    }
}
