//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ttpIrDataContext : DbContext
    {
        public ttpIrDataContext()
            : base("name=ttpIrDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<APPOINTMENT_RANK> APPOINTMENT_RANK { get; set; }
        public virtual DbSet<APPOINTMENT_ROLE> APPOINTMENT_ROLE { get; set; }
        public virtual DbSet<APPOINTMENT_ROLE_TYPE> APPOINTMENT_ROLE_TYPE { get; set; }
        public virtual DbSet<APPOINTMENT_STATE> APPOINTMENT_STATE { get; set; }
        public virtual DbSet<APPOINTMENT_STATUS> APPOINTMENT_STATUS { get; set; }
        public virtual DbSet<APPOINTMENT_TYPE> APPOINTMENT_TYPE { get; set; }
        public virtual DbSet<CONTACT_TYPE> CONTACT_TYPE { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<HEALTH_AUTHORITY> HEALTH_AUTHORITY { get; set; }
        public virtual DbSet<MD_UNDERGRAD_PROGRAM> MD_UNDERGRAD_PROGRAM { get; set; }
        public virtual DbSet<OCCUPATION> OCCUPATIONs { get; set; }
        public virtual DbSet<PAYEE> PAYEEs { get; set; }
        public virtual DbSet<PAYEE_TYPE> PAYEE_TYPE { get; set; }
        public virtual DbSet<PAYMENT_ARRANGEMENT> PAYMENT_ARRANGEMENT { get; set; }
        public virtual DbSet<PAYMENT_INFO> PAYMENT_INFO { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<PHONE_NUMBER_TYPE> PHONE_NUMBER_TYPE { get; set; }
        public virtual DbSet<PROVINCE_STATE> PROVINCE_STATE { get; set; }
        public virtual DbSet<TTPS_CONTACT_INFO> TTPS_CONTACT_INFO { get; set; }
        public virtual DbSet<IS_PROFILE_ACTIVE> IS_PROFILE_ACTIVE { get; set; }
        public virtual DbSet<IS_RETIRED> IS_RETIRED { get; set; }
        public virtual DbSet<SALUTATION> SALUTATIONS { get; set; }
    }
}
