//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.ubc.med.ttps.EnterAppointments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTPS_CONTACT_INFO
    {
        public int TTPS_CONTACT_ID { get; set; }
        public int PERSON_ID { get; set; }
        public int CONTACT_TYPE_ID { get; set; }
        public string PRIMARY_EMAIL_ADDRESS { get; set; }
        public string PRIMARY_PHONE_NUMB { get; set; }
        public string PHONE_NUMBER_EXTENSION { get; set; }
        public Nullable<int> PHONE_NUMBER_TYPE_ID { get; set; }
        public string ALTERNATE_PHONE_NUMB { get; set; }
        public string RECIPIENT_NAME { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string SUBURB_DESC { get; set; }
        public string MAILING_CD { get; set; }
        public string CITY_NAME { get; set; }
        public Nullable<int> PROV_OR_STATE_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_TS { get; set; }
        public string LAST_UPDT_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TS { get; set; }
        public string CREATED_USER { get; set; }
    
        public virtual CONTACT_TYPE CONTACT_TYPE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PHONE_NUMBER_TYPE PHONE_NUMBER_TYPE { get; set; }
        public virtual PROVINCE_STATE PROVINCE_STATE { get; set; }
    }
}
